### ISSUE TITLE
Make this NPM ready

### ISSUE THREAD

**Issue by jonyeezs** [twaggs/hubot-octopus-deploy#1]
Hi yours seems to be the most extensive plugin for octopus i can find.

Though an issue would be the commands itself. It may conflict with other people's plugins.
@bigbam505 has a good point to prefix everything with octo.

I would love to see this project on NPM so it'll be easier to maintain the hubot dependencies.

I don't mind working on this with you.

**Comment by brentm5** [comment]
@jonyeezs You are welcome to contribute to the one I have ;P
